[build]
define_macros = []
extra_compile_args = []
include_dirs = []
libraries = []
library_dirs = []
undef_macros = []

[info]
github_username = "mcflugen"
plugin_author = "Eric Hutton"
plugin_author_email = "eric.hutton@colorado.edu"
plugin_license = "MIT"
summary = "PyMT plugin for hydrotrend"

[library]
entry_point = ["Hydrotrend=bmi_hydrotrend:register_bmi_hydrotrend"]
language = "c"

[plugin]
name = "hydrotrend"
requirements = ["hydrotrend"]

