build:
  define_macros: []
  extra_compile_args: []
  include_dirs: []
  libraries:
  - bmi_hydrotrend
  library_dirs: []
  undef_macros: []
info:
  github_username: mcflugen
  plugin_author: Eric Hutton
  plugin_license: MIT
  summary: PyMT plugin for hydrotrend
library:
  entry_point:
  - Hydrotrend=hydrotrend:register_bmi_hydrotrend
  language: c
  register: ''
plugin:
  name: hydrotrend
  requirements:
  - hydrotrend
